### ISSUE TITLE
block

### ISSUE THREAD

**Issue by Tristeres** [ISurrealI/ContentCreator#1]
block？no texture

**Comment by ISurrealI** [comment]
what

**Comment by Tristeres** [comment]
how to create a block。
The created block has no texture。

**Comment by ISurrealI** [comment]
```
import contentcreator.block.Block;
import crafttweaker.block.IMaterial;

// Block.create(IMaterial material, String registryName)
Block.create(IMaterial.wood(), "example_block");
```
You can get IMaterial with bracket handler support this mod adds (e.g. <material:wood>) or like [this](https://docs.blamejared.com/1.12/en/Vanilla/Blocks/IMaterial).

you need have [Resource Loader](https://www.curseforge.com/minecraft/mc-mods/resource-loader) to add textures. It'll create "resources" named file to your minecraft instance. Create a folder named contentcreator and create blockstates named folder indside resources. Add a json file that's named same with your blocks registry name. Here's a [basic example of a blockstate json](https://github.com/GregTechCEu/GregTech/blob/master/src/main/resources/assets/gregtech/blockstates/asphalt.json).
`gregtech:blocks/stones/asphalt/asphalt` is the textures path. Replace it with something like `contentcreator:blocks/<your blocks registry name>`, and add  your texture to this path (in resources folder): `contentcreator/textures/blocks/<block name>.png`
