### ISSUE TITLE
Texture UNDERlays

### ISSUE THREAD

**Issue by Gliese-832-c** [ISurrealI/ContentCreator#12]
Similar to texture overlays, I request the addition of the ability to choose an underlay for a material. It could be used to add things like a glow for materials that emit light, or some radiation effect.
You should be able to use an overlay and an underlay at the same time.
(In fact, if possible just give the ability to select as many over- and underlays as you want, while being able to select the order in which they are applied.

**Comment by ISurrealI** [comment]
like avaritia?
I think i can add it (like colorable infinity ingot shadow)

**Comment by ISurrealI** [comment]
i give up.

**Comment by Gliese-832-c** [comment]
That's unfortunate. :(
