### ISSUE TITLE
[Not-Quite-BUG-But-Still-Pretty-Important] Material Item Metas

### ISSUE THREAD

**Issue by Gliese-832-c** [ISurrealI/ContentCreator#14]
------------------------- **Current Situation** -------------------------

When you use the material system to automatically generate bulk amounts of items, it makes an item for each part type and then makes each different material's instance of that part have a different metadata. But the problem with that is how inconsistently it is handled.

For example, let's say we have the following components: Ingot, Gear, Girder
And the following materials: Steel, Copper, Brass

The copper material only has an ingot part. Brass has ingot and gear. Steel has ingot, gear, and girder.
Now let's say, the materials are generated in the following order: Copper, Brass, Steel.

It will generate three ingots. Copper, being first, would get the item ID ingot:0. Next comes brass, ingot:1. And lastly steel, ingot:2.
However, the problems come when it tries to generate gears. Given that copper has no gear part, it will skip directly to the brass gear. But the issue arises when the brass gear gets the item ID gear:0. Steel follows that at gear:1. And lastly, the girder part, only steel has that, so steel girder becomes girder:0.

------------------------- **Why It Is a Problem** -------------------------

This is highly inconsistent. The brass parts are split up between meta 1 and 0. Steel is split up between 2, 1, and 0. This has two negative implications. Firstly, if you are using CraftTweaker to automatically generate recipes and such based on item meta, it will mess up, as different parts of the same material use different item metas. Secondly - and this one is much worse - is when you decide to change your materials. You might want to add a new material, or decide to add or remove a part from an existing material. This will completely change which meta of a given part corresponds to which material, meaning that if a modpack developer wants to change something about the material, players will have to deal with the items in their inventory and chests changing around to be made from different materials. This could probably mess up progression a lot.

One could propose the following solution: Make each material have the same parts. But not only is that an extremely ugly and unelegant solution (I don't want zinc girders or lead gears, realistically you would never make those things as they would be useless due to zinc's and lead's lack of structural strength; and it would also just clog up JEI with useless items that aren't used anywhere), this solution is also _completely invalid_, because while that would solve the issue about adding or removing parts, once you decide to add a new material things are messed up again. Even if you put it at the end of the file, the order in which the mod creates the items is seemingly random. Currently, in my script, the first material is copper_lowgrade. Following that is normal copper, after which comes tin, and then bronze. Yet the low-grade copper parts all have the meta 1, regular copper has meta 4, tin is 7, and bronze is 10. The parts with meta 0 in my game instance are material neutronium, which I put at the very end of my script file.

------------------------- **Suggested Solution** -------------------------

What I suggest as a solution to this problem is to require users to assign a numerical ID between 0 and 32767 (maximum item meta), then have each automatically generated part item use the material's ID as its meta.

For example, if you have a material tin with the ID 3, all tin parts such as tin ingot, tin plate, etc., would all have the metadata 3.

That way the metas would always be fixed to certain number, and none of the problems above would exist. You could freely add or remove parts and materials without having to worry about breaking things in a major way.

**Comment by Gliese-832-c** [comment]
Wow, that took a while to write...

**Comment by ISurrealI** [comment]
it doesn't sound it will make performance worse, also would you want jei to sort items based on material or is this good enough (now it kinda sorts based on part)

**Comment by Gliese-832-c** [comment]
Good to know it won't reduce performance. I think I would like to be sorted on material. So it would show iron ingot, plate, gear, etc. first, then copper ingot, plate, gear, then bronze ingot, plate, gear, and so on. However, it could be a config option so people could chose which one they prefer, as this is just an aesthetic decision.

**Comment by ISurrealI** [comment]
fixed it.
