### ISSUE TITLE
Content Creator doesn't work on a Forge server

### ISSUE THREAD

**Issue by Atricos** [ISurrealI/ContentCreator#19]
Content Creator cannot be launched on a Forge server, as the Forge server always crashes on load up, if the mod is included. The crashes seems to swap between
- `java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle`,
- `java.lang.NoClassDefFoundError: net/minecraft/client/particle/ParticleManager`,
- `java.lang.NoClassDefFoundError: net/minecraft/client/gui/FontRenderer`

Crash example 1 (Particle): https://pastebin.com/bNiKtj2k
Crash example 2 (ParticleManager): https://pastebin.com/9V0NbUhp
Crash example 3 (FontRenderer): https://pastebin.com/q60fbeHw

To be clear, all three of these types of crashes have occurred multiple times. The crashes don't occur in Singleplayer.

Content Creator version: ContentCreator-1.3.7-fix1.jar
Forge version: forge-1.12.2-14.23.5.2860

**Comment by ISurrealI** [comment]
fixed
