### ISSUE TITLE
Suggestion: add a sub item method for something counting as Blaze Powder in brewing

### ISSUE THREAD

**Issue by Ski-z** [ISurrealI/ContentCreator#2]
Could you add a sub item method for something counting as Blaze Powder in brewing for 1.12.2?

Like, being able to substitute an item for 1.12.2 brewing fuel?

**Comment by ISurrealI** [comment]
added it to [TTweaker](https://github.com/ISurrealI/TTweaker/commit/8c33f88b1d143e01ab7014b9f7a5de74775cb47f)
You can download it when it gets updated

**Comment by Ski-z** [comment]
You're the best!
