### ISSUE TITLE
Example fluid script crash

### ISSUE THREAD

**Issue by Primitive-Human** [ISurrealI/ContentCreator#3]
Using the following small example

```
#loader preinit

import contentcreator.fluid.Fluid;

var exampleFluid as Fluid = Fluid.create("example_fluid");
	exampleFluid.setColor(0x000000);
```

I receive a crash. https://paste.ee/p/2W6LN 

I have decent enough knowledge of CraftTweaker and Contenttweaker to know how to create scripts and where to put them. However, I haven't created any custom fluid model/texture files, as I just need to create a tinted fluid using the base textures. I know ContentTweaker can also do this, but it always generates the fluid blocks and buckets too, which I don't always need. 

Used versions:

Minecraft: 1.12.2
Forge: 14.23.5.2860
CraftTweaker: 4.1.20.675
ContentCreator: 1.3.3
ResourceLoader: 1.5.3

**Comment by ISurrealI** [comment]
Thanks for your issue, i forgot to check something lol. Should be fixed in new update

**Comment by Primitive-Human** [comment]
Now I can get the [script to generate fluids](https://i.imgur.com/lsvKy75.png), awesome.

And again, a few new issues I've found using the following script:
```

#loader preinit

import contentcreator.fluid.Fluid;

var exampleFluid as Fluid = Fluid.create("example_fluid");
	exampleFluid.setColor(0x311b4a);
	exampleFluid.addBlock(<blockmaterial:lava>);
	exampleFluid.addBucket();
	exampleFluid.setUnlocalizedName("my_liquid");
	exampleFluid.setLuminosity(6);
	exampleFluid.setDensity(4000);
	exampleFluid.setTemperature(1000);
	exampleFluid.setViscosity(5000);
```

There are no crashes or errors in the console log whatsoever. 

The issue is that there is no texture rendered when:

1. [The fluid's in any tank](https://i.imgur.com/qPU046I.png).
2. [The fluid's placed in-world](https://i.imgur.com/DvVlSIR.png).
3. [The texture/overlay ONLY appears when my head's inside the fluid block.](https://i.gyazo.com/f506a689f17331655e840877e6184f90.mp4)
