### ISSUE TITLE
Fluid textures

### ISSUE THREAD

**Issue by Primitive-Human** [ISurrealI/ContentCreator#5]
Continuation from https://github.com/ISurrealI/ContentCreator/issues/3 

Now I can get the [script to generate fluids](https://i.imgur.com/lsvKy75.png), awesome.

And again, a few new issues I've found using the following script:
```

#loader preinit

import contentcreator.fluid.Fluid;

var exampleFluid as Fluid = Fluid.create("example_fluid");
	exampleFluid.setColor(0x311b4a);
	exampleFluid.addBlock(<blockmaterial:lava>);
	exampleFluid.addBucket();
	exampleFluid.setUnlocalizedName("my_liquid");
	exampleFluid.setLuminosity(6);
	exampleFluid.setDensity(4000);
	exampleFluid.setTemperature(1000);
	exampleFluid.setViscosity(5000);
```

^ ^ By the way, on your example it says to use `addBlock(<material:lava>);` when it should be `addblock(<blockmaterial:lava>);`, or else it won't register that property.

There are no crashes or errors in the console log whatsoever. 

The issue is that there is no texture rendered when:

1. [The fluid's in any tank](https://i.imgur.com/qPU046I.png).
2. [The fluid's placed in-world](https://i.imgur.com/DvVlSIR.png).
3. [The texture/overlay ONLY appears when my head's inside the fluid block.](https://i.gyazo.com/f506a689f17331655e840877e6184f90.mp4)

**Comment by ISurrealI** [comment]
okay, this is weird it doesn't render when you set color idk why

**Comment by ISurrealI** [comment]
Okay fixed it thanks for your feedback :)
