### ISSUE TITLE
Auto generate json files

### ISSUE THREAD

**Issue by Gliese-832-c** [ISurrealI/ContentCreator#7]
The ability to somehow determine texture overlays for custom materials. For example, let's say I have an aluminum and a lead custom material. I want the aluminum material parts to look shiny, but the lead ones to look dull. This could be achieved by having texture overlays and then, when creating the material, telling which overlay to use. (For example: You could have two sets of overlay textures. Shiny and rough. Then you have multiple materials. Some materials use the shiny overlay, others use the rough one, and yet others just use no overlay.)

**Comment by ISurrealI** [comment]
You can make it now too. You can do it with resource pack stuff (which is vanilla). Don't get me wrong, i will gonna add automatic json generation, it'll speed up stuff, but you should know a bit of resource pack knowledge to make cool textures.

**Comment by Gliese-832-c** [comment]
It's nice to know that it's at least possible, but I think I will wait for automatic generation because doing anything related to resource packs manually is kind of a pain if I'm being honest...

**Comment by ISurrealI** [comment]
I will gonna add automatic model creation instead

**Comment by xJon** [comment]
> I will gonna add automatic model generation instead

Would that be instead of this empty section? https://github.com/ISurrealI/ContentCreator/wiki/Item#setting-items-texture-and-model
Just put the texture and go?

**Comment by ISurrealI** [comment]
> 

yeah
