### ISSUE TITLE
Auto-Generated Lang Files for Custom Parts

### ISSUE THREAD

**Issue by Gliese-832-c** [ISurrealI/ContentCreator#8]
It looks like the mod already has the ability to automatically generate some lang files, as can be seen with ingots and gears for example. But if you add your own type of part, it's not automatically localized. So I suggest some kind of way to allow people to input a string and have the mod automatically generate the name for custom parts. For example, if you have a girder part, you should be able to tell the mod to localize it as "_some material_ Girder". Maybe also allow the overriding of existing localization names for default parts like ingot, plate, etc.

**Comment by ISurrealI** [comment]
There was a method to add localization with crafttweaker, i will test and send information about it.

**Comment by ISurrealI** [comment]
It looks like automatic localization doesn't work well with items, blocks. Please use contentcreator/lang/en_us.lang folder created in resources folder in your instance. Can't find a there isn't a good way to automatically naming it.

**Comment by Gliese-832-c** [comment]
Wouldn't it be possible to add a thing in the code where you enter a string? Something like `part_girder.name = "Girder"`?

**Comment by ISurrealI** [comment]
item localizes itself before the mod registers it's lang

**Comment by Gliese-832-c** [comment]
The problem is, I don't want to have to do hundreds of items. Imagine if there are 50 materials and 30 parts. 50*30=1500, I don't want to do 1500 localizations.
